### ISSUE TITLE
blank canvas

### ISSUE THREAD

**Issue by FlaviuSim** [nbartlomiej/coffee-guard-caat-jessie#1]
Hi, I cannot seem to set the project up. When I install all the gems, I get a blank canvas screen still, in both modes, on bot my iphone 3GS and in Chrome and Safari.

Am I doing something wrong? I

**Comment by nbartlomiej** [comment]
Hi, you can see more details about the problem in the javascript console (e.g. in Chrome: View -> Developer -> JavaScript Console).

I think that the ./build files are missing. Try running 'guard' and hitting enter, this will trigger compilation of the whole project (I'm adding this step to the README just now).

**Comment by FlaviuSim** [comment]
First, awesome response time. I am embarrassed to admit I forgot to hit enter after starting guard. It now works as expected.
